import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import * as sass from "sass";

const projectRoot = process.cwd();

const scss = `@use "sass:meta";
@use "src/style/abstracts/variables/colors" as colors;

$vars: meta.module-variables("colors");

:root {
  @each $name, $value in $vars {
    --#{$name}: #{$value};
  }
}
`;

const result = sass.compileString(scss, {
  loadPaths: [projectRoot],
});

const css = result.css.toString();
const tokenMatches = css.matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+);/gi);
const tokens = {};

for (const match of tokenMatches) {
  const name = match[1].trim();
  const value = match[2].trim();
  tokens[name] = value;
}

const keys = Object.keys(tokens).sort();

const headerLines = [
  "/* This file is auto-generated by scripts/generate-colors.mjs */",
  "/* Do not edit this file directly. */",
  "",
];

const tokensCssLines = [
  ...headerLines,
  ":root {",
  ...keys.map((key) => `  --${key}: ${tokens[key]};`),
  "}",
  "",
];

const themeCssLines = [
  ...headerLines,
  "@theme {",
  ...keys.map((key) => `  --${key}: ${tokens[key]};`),
  "}",
  "",
];

const lines = [
  "// This file is auto-generated by scripts/generate-colors.mjs",
  "// Do not edit this file directly.",
  "",
  "export const colorTokens = {",
  ...keys.map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(tokens[key])},`),
  "} as const;",
  "",
  "export type ColorTokenName = keyof typeof colorTokens;",
  "",
];

const outputPath = path.join(projectRoot, "src/data/generated/colors.ts");
const tokensCssPath = path.join(
  projectRoot,
  "src/style/generated/tokens.css",
);
const themeCssPath = path.join(
  projectRoot,
  "src/style/generated/theme.css",
);

await mkdir(path.dirname(outputPath), { recursive: true });
await mkdir(path.dirname(tokensCssPath), { recursive: true });
await writeFile(outputPath, `${lines.join("\n")}\n`, "utf8");
await writeFile(tokensCssPath, tokensCssLines.join("\n"), "utf8");
await writeFile(themeCssPath, themeCssLines.join("\n"), "utf8");

console.log(`Generated ${outputPath}`);
console.log(`Generated ${tokensCssPath}`);
console.log(`Generated ${themeCssPath}`);
